package com.mobile.fodein.tools

object Constants {
    val HTTPBase = "http://192.168.1.113:80/fdi/index.php/services/"
    val SERVICE_LOGIN = "verifylogin"
    val SERVICE_REGISTER_USER = "registeruser"
    val SERVICE_GET_DISTRICT = "getdistricts"
    val SERVICE_GET_UNITS = "getunits"
    val SERVICE_GET_PROJECTS = "getprojects"
    val SERVICE_GET_FORMS = ""
    val SERVICE_UPLOAD_FORMS = "registerform"
    val CONTENT_TYPE = "application/json; charset=utf-8"
    val USER_NAME = "name"
    val USER_USER = "user"
    val USER_IDCARD = "idCard"
    val USER_EMAIL = "email"
    val USER_PASSWORD = "password"
    val USER_PHONE = "phone"
    val USER_ADDRESS = "address"
    val USER_DESCRIPTION = "description"
    val USER_ROLL = "roll"
    val USER_UNIT = "unit_id"
    val USER_ID = "id"
    val USER_TOKEN = "token"
    val USER_IMAGE = "image"
    val CACHE_LIST_DISTRICT_MODEL = "list_district_model"
    val CACHE_LIST_UNITY_MODEL = "list_unity_model"
    val CACHE_LIST_PROJECT_MODEL = "list_project_model"
    val CACHE_LIST_FORM_MODEL = "list_form_model"
    val CACHE_USER_MODEL = "user_model"
}